import { expect, test, type Page, type TestInfo } from "@playwright/test"
import { startAdministrationBackend } from "./helpers/administration-backend"
import { captureVerificationSection } from "./helpers/verification-capture"
import { captureAccessDialog } from "./helpers/administration-capture"

let backend: Awaited<ReturnType<typeof startAdministrationBackend>>
test.beforeAll(async () => { backend = await startAdministrationBackend() })
test.afterAll(async () => { await backend.stop() })
test.beforeEach(async ({ context }) => { await context.route("**/*", (route) => new URL(route.request().url()).origin === backend.server.baseUrl ? route.continue() : route.abort("blockedbyclient")) })
const panel = (page: Page) => page.locator('section[aria-labelledby="access-review-workspace"]')
async function approveAndSend(page: Page, info: TestInfo) {
  const review = panel(page)
  await expect(review.getByRole("button", { name: "Approve access request" })).toBeEnabled()
  await captureVerificationSection(page, info, { name: "review", section: "access-review-workspace" })
  await review.getByRole("button", { name: "Approve access request" }).click()
  await expect(review.getByRole("button", { name: "Send approved access request" })).toBeDisabled()
  await captureVerificationSection(page, info, { name: "approved", section: "access-review-workspace" })
  await review.getByRole("checkbox").focus(); await page.keyboard.press("Space")
  await review.getByRole("button", { name: "Send approved access request" }).focus()
  await captureVerificationSection(page, info, { name: "keyboard-ready", section: "access-review-workspace" })
  await page.keyboard.press("Enter")
  await expect(review.getByText("Accepted by Google", { exact: true })).toBeVisible()
  await expect(review.getByText("Independently confirmed", { exact: true })).toBeVisible()
  await captureVerificationSection(page, info, { name: "outcome", section: "access-review-workspace" })
}
for (const width of [375, 768, 1280]) test.describe(`Reviewed access at ${width}px`, () => {
  test.use({ viewport: { width, height: 1100 } })
  for (const scope of ["location", "account"] as const) test(`invites at the exact ${scope} scope and restores the pending invitation outcome`, async ({ page }, info) => {
    const fixture = await backend.accessFixture(page); await fixture.open()
    await expect(page.getByText("Fixture Account Owner", { exact: true })).toBeVisible()
    await captureVerificationSection(page, info, { name: "location-admins", section: "people-location" })
    await captureVerificationSection(page, info, { name: "account-admins", section: "people-account" })
    await captureVerificationSection(page, info, { name: "lifecycle-consequences", section: "danger-zone-heading" })
    await page.getByRole("button", { name: "Add administrator" }).click()
    await captureAccessDialog(page, info, "invitation-empty")
    if (scope === "account") { await page.getByRole("combobox", { name: "Scope", exact: true }).click(); await page.getByRole("option", { name: "The whole Google account", exact: true }).click() }
    await page.getByLabel("Email address", { exact: true }).fill("invitee@example.test")
    await captureAccessDialog(page, info, "invitation-filled")
    await page.getByRole("button", { name: "Review invitation", exact: true }).click()
    expect(fixture.writes()).toHaveLength(0)
    await approveAndSend(page, info)
    expect(fixture.writes()).toHaveLength(1)
    expect(fixture.writes()[0]).toMatchObject({ body: { admin: "invitee@example.test", role: "MANAGER" } })
    expect(fixture.writes()[0].path).toContain(`${scope === "account" ? fixture.connection.googleAccountName : fixture.linked.googleLocationName}/admins`)
    await expect(panel(page).getByText("Administrator invitation listed; access awaits acceptance", { exact: true })).toBeVisible()
    await page.reload(); await page.getByRole("button", { name: "Open outcome", exact: true }).click()
    await expect(panel(page).getByText("Independently confirmed", { exact: true })).toBeVisible()
    await captureVerificationSection(page, info, { name: "restored", section: "access-review-workspace" })
    await captureVerificationSection(page, info, { name: "saved-work", section: "access-saved-work" })
    expect(fixture.writes()).toHaveLength(1)
  })
  test("reviews the current and proposed role before changing the exact administrator", async ({ page }, info) => {
    const fixture = await backend.accessFixture(page); await fixture.open()
    await page.getByRole("combobox", { name: "Role for manager@example.test", exact: true }).click()
    await page.getByRole("option", { name: "Owner", exact: true }).click()
    await page.getByRole("button", { name: "Review role change", exact: true }).click()
    await expect(panel(page).locator("dl > div").filter({ has: page.getByText("Current role", { exact: true }) }).locator("dd")).toHaveText("Manager")
    await expect(panel(page).getByText("Administrator manager@example.test on this listing", { exact: true })).toBeVisible()
    await expect(panel(page).getByText(/^Google reference: locations\/.+\/admins\/manager$/)).toBeVisible()
    await expect(page.getByRole("combobox", { name: "Role for manager@example.test", exact: true })).toHaveText("Manager")
    await approveAndSend(page, info)
    expect(fixture.writes()).toHaveLength(1)
    expect(fixture.state.locationAdmins[1].role).toBe("OWNER")
    await expect(page.getByRole("combobox", { name: "Role for manager@example.test", exact: true })).toHaveText("Owner")
  })
  test("reviews administrator removal after the typed listing confirmation", async ({ page }, info) => {
    const fixture = await backend.accessFixture(page); await fixture.open()
    await page.getByRole("button", { name: "Remove manager@example.test", exact: true }).click()
    const confirm = page.getByRole("button", { name: "Review administrator removal", exact: true })
    await expect(confirm).toBeDisabled()
    const [listing] = await backend.admin`select name from location where id = ${fixture.linked.locationId}`
    await page.getByLabel(/Type the location's name/i).fill(String(listing.name))
    await confirm.click(); expect(fixture.writes()).toHaveLength(0)
    await approveAndSend(page, info)
    await expect(panel(page).getByText("Reviewed administrator no longer listed", { exact: true })).toBeVisible()
    expect(fixture.writes()).toHaveLength(1)
  })
  for (const action of ["accept", "decline"] as const) test(`reviews and independently confirms invitation ${action}`, async ({ page }, info) => {
    const fixture = await backend.accessFixture(page); await fixture.open()
    await page.getByRole("button", { name: action === "accept" ? "Review acceptance" : "Review decline", exact: true }).click()
    expect(fixture.writes()).toHaveLength(0)
    await expect(panel(page).getByText("Pending invitation for the connected Google account", { exact: true })).toBeVisible()
    await expect(panel(page).getByText(/^Google reference: accounts\/.+\/invitations\/pending$/)).toBeVisible()
    await expect(panel(page).getByText("Invited role", { exact: true })).toBeVisible()
    await expect(panel(page).getByText("Current role", { exact: true })).toHaveCount(0)
    await approveAndSend(page, info)
    await expect(panel(page).getByText(action === "accept" ? "Reviewed account and role independently accessible" : "Reviewed invitation no longer pending", { exact: true })).toBeVisible()
    expect(fixture.writes()).toHaveLength(1)
  })
})
