import { test, expect, type Page, type TestInfo } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { matchLinkIds, setupMatchLink } from "./helpers/onboarding-match-link"

const panel = (page: Page) => page.locator('section[aria-labelledby="existing-match-heading"]')
const status = (page: Page) => page.locator('section[aria-labelledby="match-link-status-heading"]')

async function prepareReview(page: Page) {
  await panel(page).getByRole("button", { name: "Check accessible matches" }).click()
  await panel(page).getByRole("button", { name: "Select this existing match" }).click()
  await panel(page).getByRole("textbox", { name: "Local name for this existing listing" }).fill("Distinct local business")
  await panel(page).getByRole("button", { name: "Review existing listing link" }).click()
  await expect(page).toHaveURL(new RegExp(`onboardingMatchLinkReview=${matchLinkIds.review}`))
  await expect(panel(page).getByText("Google resource", { exact: true })).toBeVisible()
}

async function capture(page: Page, info: TestInfo, name: string, width: number, selector = 'section[aria-labelledby="existing-match-heading"]') {
  await page.setViewportSize({ width, height: 3000 })
  await page.locator(selector).screenshot({ path: info.outputPath(`match-link-${name}-${width}.png`), animations: "disabled" })
  await page.setViewportSize({ width, height: 1000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
}

for (const width of [375, 768, 1280]) {
  test(`reviews and links one exact existing resource at ${width}px`, async ({ page, baseURL }, info) => {
    await page.setViewportSize({ width, height: 1000 })
    const fixture = await setupMatchLink(page, baseURL)
    await panel(page).getByRole("button", { name: "Check accessible matches" }).click()
    await expect(panel(page).getByRole("button", { name: "Select this existing match" })).toHaveCount(1)
    await expect(panel(page).getByText(/Not found in this selected account/)).toBeVisible()
    await expect(panel(page).getByText(/not supplied enough consistent identity/)).toBeVisible()
    await expect(panel(page).getByText(/Multiple resources share this identity/)).toBeVisible()
    await capture(page, info, "discovery", width)
    const select = panel(page).getByRole("button", { name: "Select this existing match" })
    await select.focus()
    await page.keyboard.press("Enter")
    await expect(page.getByRole("textbox", { name: "Business name", exact: true })).toBeDisabled()
    await panel(page).getByRole("textbox", { name: "Local name for this existing listing" }).fill("Distinct local business")
    await capture(page, info, "selected", width)
    await panel(page).getByRole("button", { name: "Review existing listing link" }).click()
    await expect(panel(page).getByText("Unknown", { exact: true })).toBeVisible()
    await expect(panel(page).getByText("locations/exact-owned", { exact: true })).toBeVisible()
    await expect(panel(page).getByText("Distinct local business", { exact: true })).toBeVisible()
    await capture(page, info, "review", width)
    expect((await new AxeBuilder({ page }).include('section[aria-labelledby="existing-match-heading"]').analyze()).violations).toEqual([])
    await page.reload()
    await expect(panel(page).getByText("Distinct local business", { exact: true })).toBeVisible()
    await panel(page).getByRole("button", { name: "Approve existing listing link" }).click()
    const link = panel(page).getByRole("button", { name: "Link approved existing listing" })
    await expect(link).toBeDisabled()
    await capture(page, info, "approved", width)
    await panel(page).getByRole("checkbox").focus()
    await page.keyboard.press("Space")
    await page.keyboard.press("Tab")
    await expect(link).toBeFocused()
    await page.keyboard.press("Enter")
    await expect(status(page).getByRole("heading")).toHaveText("Existing Google listing linked")
    await capture(page, info, "linked", width, 'section[aria-labelledby="match-link-status-heading"]')
    await page.reload()
    await expect(status(page).getByRole("link", { name: "Open linked listing" })).toBeVisible()
    await expect(page.getByRole("button", { name: "Validate and review creation" })).toHaveCount(0)
    await status(page).getByRole("button", { name: "Refresh link status" }).click()
    expect(fixture.read()).toMatchObject({ submissions: 1, previews: 1, approvals: 1 })
  })

  test(`keeps discovery failure and mapping conflicts actionable at ${width}px`, async ({ page, baseURL }, info) => {
    await page.setViewportSize({ width, height: 1000 })
    const fixture = await setupMatchLink(page, baseURL)
    fixture.failDiscovery()
    await panel(page).getByRole("button", { name: "Check accessible matches" }).click()
    await expect(panel(page).getByRole("alert")).toContainText("not evidence that a new listing is needed")
    await expect(panel(page).getByRole("button", { name: "Select this existing match" })).toHaveCount(0)
    await capture(page, info, "discovery-error", width)
    fixture.setConflicts(["external_assignment", "existing_link", "local_name", "webhook_assignment"])
    await prepareReview(page)
    await expect(panel(page).getByRole("alert")).toContainText("Resolve these mapping conflicts")
    await expect(panel(page).getByRole("button", { name: "Approve existing listing link" })).toHaveCount(0)
    await expect(panel(page).getByRole("button", { name: "Link approved existing listing" })).toHaveCount(0)
    await capture(page, info, "conflicts", width)
    expect((await new AxeBuilder({ page }).include('section[aria-labelledby="existing-match-heading"]').analyze()).violations).toEqual([])
    expect(fixture.read()).toMatchObject({ submissions: 0, approvals: 0, previews: 1 })
  })

  test(`restores pending and failed link status at ${width}px`, async ({ page, baseURL }, info) => {
    await page.setViewportSize({ width, height: 1000 })
    const fixture = await setupMatchLink(page, baseURL, { initialState: "pending", statusError: true })
    await expect(page.getByRole("button", { name: "Retry link status" })).toBeVisible()
    await capture(page, info, "status-error", width, 'section[aria-labelledby="onboarding-drafts-heading"] div[role="alert"]')
    fixture.restoreStatus()
    await page.getByRole("button", { name: "Retry link status" }).click()
    await expect(status(page).getByRole("heading")).toHaveText("Existing listing link in progress")
    await capture(page, info, "pending", width, 'section[aria-labelledby="match-link-status-heading"]')
    expect((await new AxeBuilder({ page }).include('section[aria-labelledby="match-link-status-heading"]').analyze()).violations).toEqual([])
    fixture.setOperation("failed")
    await status(page).getByRole("button", { name: "Refresh link status" }).click()
    await expect(status(page).getByRole("heading")).toHaveText("Existing listing link needs recovery")
    await capture(page, info, "failed", width, 'section[aria-labelledby="match-link-status-heading"]')
    expect(fixture.read().submissions).toBe(0)
  })
}

test("requires another approver and restores their exact approved review", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL, { secondApprover: true })
  await prepareReview(page)
  await expect(panel(page).getByText(/different authorised owner or admin/)).toBeVisible()
  await expect(panel(page).getByRole("button", { name: "Approve existing listing link" })).toBeDisabled()
  fixture.approveElsewhere()
  await panel(page).getByRole("button", { name: "Refresh link review" }).click()
  await expect(panel(page).getByText("This mapping is approved.")).toBeVisible()
  expect(fixture.read()).toMatchObject({ approvals: 0, submissions: 0 })
})

test("restores a completed mapping after the submission response is lost", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL, { lostResponse: true })
  await prepareReview(page)
  await panel(page).getByRole("button", { name: "Approve existing listing link" }).click()
  await panel(page).getByRole("checkbox").check()
  await panel(page).getByRole("button", { name: "Link approved existing listing" }).click()
  await expect(status(page).getByRole("heading")).toHaveText("Existing Google listing linked")
  await page.reload()
  await expect(status(page).getByRole("heading")).toHaveText("Existing Google listing linked")
  expect(fixture.read().submissions).toBe(1)
})

test("restores a failed operation review and retries its same intent", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL, { initialState: "failed" })
  await expect(status(page).getByRole("heading")).toHaveText("Existing listing link needs recovery")
  await status(page).getByRole("button", { name: "Restore link review" }).click()
  await expect(panel(page).getByText("This mapping is approved.")).toBeVisible()
  await panel(page).getByRole("checkbox").check()
  await panel(page).getByRole("button", { name: "Link approved existing listing" }).click()
  await expect(status(page).getByRole("heading")).toHaveText("Existing Google listing linked")
  expect(fixture.read()).toMatchObject({ submissions: 1, previews: 0, approvals: 0 })
})

test("holds editing and creation until pending or unavailable link status is restored", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL, { initialState: "pending", statusError: true })
  await expect(page.getByRole("button", { name: "Retry link status" })).toBeVisible()
  await expect(page.getByRole("textbox", { name: "Business name", exact: true })).toHaveCount(0)
  fixture.restoreStatus()
  await page.getByRole("button", { name: "Retry link status" }).click()
  await expect(status(page).getByRole("heading")).toHaveText("Existing listing link in progress")
  await expect(status(page).getByRole("button", { name: "Restore link review" })).toHaveCount(0)
  fixture.setOperation("failed")
  await status(page).getByRole("button", { name: "Refresh link status" }).click()
  await expect(status(page).getByRole("heading")).toHaveText("Existing listing link needs recovery")
  await expect(page.getByRole("textbox", { name: "Business name", exact: true })).toBeEnabled()
  expect(fixture.read().submissions).toBe(0)
})

test("guards unsaved link decisions and rejects an expired restored review", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL)
  await panel(page).getByRole("button", { name: "Check accessible matches" }).click()
  await panel(page).getByRole("button", { name: "Select this existing match" }).click()
  await page.getByRole("link", { name: "Saved drafts", exact: true }).click()
  await expect(page.getByRole("alertdialog")).toBeVisible()
  await page.getByRole("button", { name: "Keep editing" }).click()
  await panel(page).getByRole("button", { name: "Discard link decision" }).click()
  await expect(page.getByRole("textbox", { name: "Business name", exact: true })).toBeEnabled()
  await prepareReview(page)
  fixture.expireReview()
  await page.reload()
  await expect(panel(page).getByRole("alert")).toBeVisible()
  await expect(panel(page).getByRole("button", { name: "Approve existing listing link" })).toHaveCount(0)
  await expect(panel(page).getByRole("button", { name: "Start a fresh link review" })).toBeVisible()
  expect(fixture.read()).toMatchObject({ submissions: 0, approvals: 0 })
})

test("shows recovery when a failed operation's original search is no longer saved", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL, { initialState: "failed" })
  fixture.clearSearch()
  await page.reload()
  await status(page).getByRole("button", { name: "Restore link review" }).click()
  await expect(panel(page).getByRole("alert")).toBeVisible()
  await panel(page).getByRole("button", { name: "Start a fresh link review" }).click()
  await expect(page).not.toHaveURL(/onboardingMatchLinkReview/)
  await expect(page.getByRole("textbox", { name: "Business name", exact: true })).toBeEnabled()
  expect(fixture.read().submissions).toBe(0)
})

test("blocks another submission while the recorded link outcome is being restored", async ({ page, baseURL }) => {
  const fixture = await setupMatchLink(page, baseURL)
  await prepareReview(page)
  await panel(page).getByRole("button", { name: "Approve existing listing link" }).click()
  await panel(page).getByRole("checkbox").check()
  fixture.blockStatus()
  try {
    await panel(page).getByRole("button", { name: "Link approved existing listing" }).click()
    await expect.poll(() => fixture.read().statusReads).toBeGreaterThan(1)
    await expect(panel(page).getByRole("button", { name: "Link approved existing listing" })).toBeDisabled()
    expect(fixture.read().submissions).toBe(1)
  } finally { fixture.releaseStatus() }
  await expect(status(page).getByRole("heading")).toHaveText("Existing Google listing linked")
})
