import { z } from "zod"

// Generated from the pinned Google Lodging v1 discovery schema, revision 20260928.

const propertySchema = z.strictObject({
  builtYear: z.number().int().min(-2147483648).max(2147483647).optional(),
  builtYearException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  floorsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  floorsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  lastRenovatedYear: z.number().int().min(-2147483648).max(2147483647).optional(),
  lastRenovatedYearException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  roomsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  roomsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const languageSpokenSchema = z.strictObject({
  languageCode: z.string().min(1),
  spoken: z.boolean().optional(),
  spokenException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const servicesSchema = z.strictObject({
  baggageStorage: z.boolean().optional(),
  baggageStorageException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  concierge: z.boolean().optional(),
  conciergeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  convenienceStore: z.boolean().optional(),
  convenienceStoreException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  currencyExchange: z.boolean().optional(),
  currencyExchangeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  elevator: z.boolean().optional(),
  elevatorException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  frontDesk: z.boolean().optional(),
  frontDeskException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  fullServiceLaundry: z.boolean().optional(),
  fullServiceLaundryException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  giftShop: z.boolean().optional(),
  giftShopException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  languagesSpoken: z.array(languageSpokenSchema).optional(),
  selfServiceLaundry: z.boolean().optional(),
  selfServiceLaundryException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  socialHour: z.boolean().optional(),
  socialHourException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  twentyFourHourFrontDesk: z.boolean().optional(),
  twentyFourHourFrontDeskException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  wakeUpCalls: z.boolean().optional(),
  wakeUpCallsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const housekeepingSchema = z.strictObject({
  dailyHousekeeping: z.boolean().optional(),
  dailyHousekeepingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  housekeepingAvailable: z.boolean().optional(),
  housekeepingAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  turndownService: z.boolean().optional(),
  turndownServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const parkingSchema = z.strictObject({
  electricCarChargingStations: z.boolean().optional(),
  electricCarChargingStationsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeParking: z.boolean().optional(),
  freeParkingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeSelfParking: z.boolean().optional(),
  freeSelfParkingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeValetParking: z.boolean().optional(),
  freeValetParkingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  parkingAvailable: z.boolean().optional(),
  parkingAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  selfParkingAvailable: z.boolean().optional(),
  selfParkingAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  valetParkingAvailable: z.boolean().optional(),
  valetParkingAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const wellnessSchema = z.strictObject({
  doctorOnCall: z.boolean().optional(),
  doctorOnCallException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  ellipticalMachine: z.boolean().optional(),
  ellipticalMachineException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  fitnessCenter: z.boolean().optional(),
  fitnessCenterException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeFitnessCenter: z.boolean().optional(),
  freeFitnessCenterException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeWeights: z.boolean().optional(),
  freeWeightsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  massage: z.boolean().optional(),
  massageException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  salon: z.boolean().optional(),
  salonException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  sauna: z.boolean().optional(),
  saunaException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  spa: z.boolean().optional(),
  spaException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  treadmill: z.boolean().optional(),
  treadmillException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  weightMachine: z.boolean().optional(),
  weightMachineException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const physicalDistancingSchema = z.strictObject({
  commonAreasPhysicalDistancingArranged: z.boolean().optional(),
  commonAreasPhysicalDistancingArrangedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  physicalDistancingRequired: z.boolean().optional(),
  physicalDistancingRequiredException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  safetyDividers: z.boolean().optional(),
  safetyDividersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  sharedAreasLimitedOccupancy: z.boolean().optional(),
  sharedAreasLimitedOccupancyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  wellnessAreasHavePrivateSpaces: z.boolean().optional(),
  wellnessAreasHavePrivateSpacesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const personalProtectionSchema = z.strictObject({
  commonAreasOfferSanitizingItems: z.boolean().optional(),
  commonAreasOfferSanitizingItemsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  faceMaskRequired: z.boolean().optional(),
  faceMaskRequiredException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  guestRoomHygieneKitsAvailable: z.boolean().optional(),
  guestRoomHygieneKitsAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  protectiveEquipmentAvailable: z.boolean().optional(),
  protectiveEquipmentAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const increasedFoodSafetySchema = z.strictObject({
  diningAreasAdditionalSanitation: z.boolean().optional(),
  diningAreasAdditionalSanitationException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  disposableFlatware: z.boolean().optional(),
  disposableFlatwareException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  foodPreparationAndServingAdditionalSafety: z.boolean().optional(),
  foodPreparationAndServingAdditionalSafetyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  individualPackagedMeals: z.boolean().optional(),
  individualPackagedMealsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  singleUseFoodMenus: z.boolean().optional(),
  singleUseFoodMenusException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const minimizedContactSchema = z.strictObject({
  contactlessCheckinCheckout: z.boolean().optional(),
  contactlessCheckinCheckoutException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  digitalGuestRoomKeys: z.boolean().optional(),
  digitalGuestRoomKeysException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  housekeepingScheduledRequestOnly: z.boolean().optional(),
  housekeepingScheduledRequestOnlyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  noHighTouchItemsCommonAreas: z.boolean().optional(),
  noHighTouchItemsCommonAreasException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  noHighTouchItemsGuestRooms: z.boolean().optional(),
  noHighTouchItemsGuestRoomsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  plasticKeycardsDisinfected: z.boolean().optional(),
  plasticKeycardsDisinfectedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  roomBookingsBuffer: z.boolean().optional(),
  roomBookingsBufferException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const enhancedCleaningSchema = z.strictObject({
  commercialGradeDisinfectantCleaning: z.boolean().optional(),
  commercialGradeDisinfectantCleaningException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  commonAreasEnhancedCleaning: z.boolean().optional(),
  commonAreasEnhancedCleaningException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  employeesTrainedCleaningProcedures: z.boolean().optional(),
  employeesTrainedCleaningProceduresException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  employeesTrainedThoroughHandWashing: z.boolean().optional(),
  employeesTrainedThoroughHandWashingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  employeesWearProtectiveEquipment: z.boolean().optional(),
  employeesWearProtectiveEquipmentException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  guestRoomsEnhancedCleaning: z.boolean().optional(),
  guestRoomsEnhancedCleaningException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const healthAndSafetySchema = z.strictObject({
  enhancedCleaning: enhancedCleaningSchema.optional(),
  increasedFoodSafety: increasedFoodSafetySchema.optional(),
  minimizedContact: minimizedContactSchema.optional(),
  personalProtection: personalProtectionSchema.optional(),
  physicalDistancing: physicalDistancingSchema.optional(),
})

const energyEfficiencySchema = z.strictObject({
  carbonFreeEnergySources: z.boolean().optional(),
  carbonFreeEnergySourcesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  energyConservationProgram: z.boolean().optional(),
  energyConservationProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  energyEfficientHeatingAndCoolingSystems: z.boolean().optional(),
  energyEfficientHeatingAndCoolingSystemsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  energyEfficientLighting: z.boolean().optional(),
  energyEfficientLightingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  energySavingThermostats: z.boolean().optional(),
  energySavingThermostatsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  independentOrganizationAuditsEnergyUse: z.boolean().optional(),
  independentOrganizationAuditsEnergyUseException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const waterConservationSchema = z.strictObject({
  independentOrganizationAuditsWaterUse: z.boolean().optional(),
  independentOrganizationAuditsWaterUseException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  linenReuseProgram: z.boolean().optional(),
  linenReuseProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  towelReuseProgram: z.boolean().optional(),
  towelReuseProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterSavingShowers: z.boolean().optional(),
  waterSavingShowersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterSavingSinks: z.boolean().optional(),
  waterSavingSinksException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterSavingToilets: z.boolean().optional(),
  waterSavingToiletsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const wasteReductionSchema = z.strictObject({
  compostableFoodContainersAndCutlery: z.boolean().optional(),
  compostableFoodContainersAndCutleryException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  compostsExcessFood: z.boolean().optional(),
  compostsExcessFoodException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  donatesExcessFood: z.boolean().optional(),
  donatesExcessFoodException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  foodWasteReductionProgram: z.boolean().optional(),
  foodWasteReductionProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  noSingleUsePlasticStraws: z.boolean().optional(),
  noSingleUsePlasticStrawsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  noSingleUsePlasticWaterBottles: z.boolean().optional(),
  noSingleUsePlasticWaterBottlesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  noStyrofoamFoodContainers: z.boolean().optional(),
  noStyrofoamFoodContainersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  recyclingProgram: z.boolean().optional(),
  recyclingProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  refillableToiletryContainers: z.boolean().optional(),
  refillableToiletryContainersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  safelyDisposesBatteries: z.boolean().optional(),
  safelyDisposesBatteriesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  safelyDisposesElectronics: z.boolean().optional(),
  safelyDisposesElectronicsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  safelyDisposesLightbulbs: z.boolean().optional(),
  safelyDisposesLightbulbsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  safelyHandlesHazardousSubstances: z.boolean().optional(),
  safelyHandlesHazardousSubstancesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  soapDonationProgram: z.boolean().optional(),
  soapDonationProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  toiletryDonationProgram: z.boolean().optional(),
  toiletryDonationProgramException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterBottleFillingStations: z.boolean().optional(),
  waterBottleFillingStationsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const ecoCertificationSchema = z.strictObject({
  awarded: z.boolean().optional(),
  awardedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  ecoCertificate: z.enum(["ECO_CERTIFICATE_UNSPECIFIED","ISO14001","ISO50001","ASIAN_ECOTOURISM","BIOSPHERE_RESPOSNIBLE_TOURISM","BUREAU_VERITAS","CONTROL_UNION","EARTHCHECK","ECO_CERTIFICATION_MALTA","ECOTOURISM_AUSTRALIAS_ECO","GREAT_GREEN_DEAL","GREEN_GLOBE","GREEN_GROWTH2050","GREEN_KEY","GREEN_KEY_ECO_RATING","GREEN_SEAL","GREEN_STAR","GREEN_TOURISM_ACTIVE","HILTON_LIGHTSTAY","HOSTELLING_INTERNATIONALS_QUALITY_AND_SUSTAINABILITY","HOTELES_MAS_VERDES","NORDIC_SWAN_ECOLABEL","PREFERRED_BY_NATURE_SUSTAINABLE_TOURISM","SUSTAINABLE_TRAVEL_IRELAND","TOF_TIGERS_INITITIVES_PUG","TRAVELIFE","UNITED_CERTIFICATION_SYSTEMS_LIMITED","VIREO_SRL"]),
})

const sustainabilityCertificationsSchema = z.strictObject({
  breeamCertification: z.enum(["BREEAM_CERTIFICATION_UNSPECIFIED","NO_BREEAM_CERTIFICATION","BREEAM_PASS","BREEAM_GOOD","BREEAM_VERY_GOOD","BREEAM_EXCELLENT","BREEAM_OUTSTANDING"]).optional(),
  breeamCertificationException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  ecoCertifications: z.array(ecoCertificationSchema).optional(),
  leedCertification: z.enum(["LEED_CERTIFICATION_UNSPECIFIED","NO_LEED_CERTIFICATION","LEED_CERTIFIED","LEED_SILVER","LEED_GOLD","LEED_PLATINUM"]).optional(),
  leedCertificationException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const sustainableSourcingSchema = z.strictObject({
  ecoFriendlyToiletries: z.boolean().optional(),
  ecoFriendlyToiletriesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  locallySourcedFoodAndBeverages: z.boolean().optional(),
  locallySourcedFoodAndBeveragesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  organicCageFreeEggs: z.boolean().optional(),
  organicCageFreeEggsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  organicFoodAndBeverages: z.boolean().optional(),
  organicFoodAndBeveragesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  responsiblePurchasingPolicy: z.boolean().optional(),
  responsiblePurchasingPolicyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  responsiblySourcesSeafood: z.boolean().optional(),
  responsiblySourcesSeafoodException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  veganMeals: z.boolean().optional(),
  veganMealsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  vegetarianMeals: z.boolean().optional(),
  vegetarianMealsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const sustainabilitySchema = z.strictObject({
  energyEfficiency: energyEfficiencySchema.optional(),
  sustainabilityCertifications: sustainabilityCertificationsSchema.optional(),
  sustainableSourcing: sustainableSourcingSchema.optional(),
  wasteReduction: wasteReductionSchema.optional(),
  waterConservation: waterConservationSchema.optional(),
})

const lodgingMetadataSchema = z.strictObject({
  updateTime: z.iso.datetime({ offset: true }).optional(),
})

const transportationSchema = z.strictObject({
  airportShuttle: z.boolean().optional(),
  airportShuttleException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  carRentalOnProperty: z.boolean().optional(),
  carRentalOnPropertyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeAirportShuttle: z.boolean().optional(),
  freeAirportShuttleException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freePrivateCarService: z.boolean().optional(),
  freePrivateCarServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  localShuttle: z.boolean().optional(),
  localShuttleException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  privateCarService: z.boolean().optional(),
  privateCarServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  transfer: z.boolean().optional(),
  transferException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const accessibilitySchema = z.strictObject({
  mobilityAccessible: z.boolean().optional(),
  mobilityAccessibleElevator: z.boolean().optional(),
  mobilityAccessibleElevatorException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleParking: z.boolean().optional(),
  mobilityAccessibleParkingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessiblePool: z.boolean().optional(),
  mobilityAccessiblePoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const activitiesSchema = z.strictObject({
  beachAccess: z.boolean().optional(),
  beachAccessException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  beachFront: z.boolean().optional(),
  beachFrontException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  bicycleRental: z.boolean().optional(),
  bicycleRentalException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  boutiqueStores: z.boolean().optional(),
  boutiqueStoresException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  casino: z.boolean().optional(),
  casinoException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeBicycleRental: z.boolean().optional(),
  freeBicycleRentalException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeWatercraftRental: z.boolean().optional(),
  freeWatercraftRentalException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  gameRoom: z.boolean().optional(),
  gameRoomException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  golf: z.boolean().optional(),
  golfException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  horsebackRiding: z.boolean().optional(),
  horsebackRidingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  nightclub: z.boolean().optional(),
  nightclubException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  privateBeach: z.boolean().optional(),
  privateBeachException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  scuba: z.boolean().optional(),
  scubaException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  snorkeling: z.boolean().optional(),
  snorkelingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tennis: z.boolean().optional(),
  tennisException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  watercraftRental: z.boolean().optional(),
  watercraftRentalException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterSkiing: z.boolean().optional(),
  waterSkiingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const foodAndDrinkSchema = z.strictObject({
  bar: z.boolean().optional(),
  barException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  breakfastAvailable: z.boolean().optional(),
  breakfastAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  breakfastBuffet: z.boolean().optional(),
  breakfastBuffetException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  buffet: z.boolean().optional(),
  buffetException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  dinnerBuffet: z.boolean().optional(),
  dinnerBuffetException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  freeBreakfast: z.boolean().optional(),
  freeBreakfastException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  restaurant: z.boolean().optional(),
  restaurantException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  restaurantsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  restaurantsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  roomService: z.boolean().optional(),
  roomServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tableService: z.boolean().optional(),
  tableServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  twentyFourHourRoomService: z.boolean().optional(),
  twentyFourHourRoomServiceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  vendingMachine: z.boolean().optional(),
  vendingMachineException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaAccessibilitySchema = z.strictObject({
  adaCompliantUnit: z.boolean().optional(),
  adaCompliantUnitException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hearingAccessibleDoorbell: z.boolean().optional(),
  hearingAccessibleDoorbellException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hearingAccessibleFireAlarm: z.boolean().optional(),
  hearingAccessibleFireAlarmException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hearingAccessibleUnit: z.boolean().optional(),
  hearingAccessibleUnitException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleBathtub: z.boolean().optional(),
  mobilityAccessibleBathtubException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleShower: z.boolean().optional(),
  mobilityAccessibleShowerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleToilet: z.boolean().optional(),
  mobilityAccessibleToiletException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobilityAccessibleUnit: z.boolean().optional(),
  mobilityAccessibleUnitException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaSleepingSchema = z.strictObject({
  bedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  bedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  bunkBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  bunkBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  cribsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  cribsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  doubleBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  doubleBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  featherPillows: z.boolean().optional(),
  featherPillowsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hypoallergenicBedding: z.boolean().optional(),
  hypoallergenicBeddingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kingBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  kingBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  memoryFoamPillows: z.boolean().optional(),
  memoryFoamPillowsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  otherBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  otherBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  queenBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  queenBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  rollAwayBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  rollAwayBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  singleOrTwinBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  singleOrTwinBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  sofaBedsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  sofaBedsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  syntheticPillows: z.boolean().optional(),
  syntheticPillowsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaLayoutSchema = z.strictObject({
  balcony: z.boolean().optional(),
  balconyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  livingAreaSqMeters: z.number().optional(),
  livingAreaSqMetersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  loft: z.boolean().optional(),
  loftException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  nonSmoking: z.boolean().optional(),
  nonSmokingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  patio: z.boolean().optional(),
  patioException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  stairs: z.boolean().optional(),
  stairsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaEatingSchema = z.strictObject({
  coffeeMaker: z.boolean().optional(),
  coffeeMakerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  cookware: z.boolean().optional(),
  cookwareException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  dishwasher: z.boolean().optional(),
  dishwasherException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  indoorGrill: z.boolean().optional(),
  indoorGrillException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kettle: z.boolean().optional(),
  kettleException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kitchenAvailable: z.boolean().optional(),
  kitchenAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  microwave: z.boolean().optional(),
  microwaveException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  minibar: z.boolean().optional(),
  minibarException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  outdoorGrill: z.boolean().optional(),
  outdoorGrillException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  oven: z.boolean().optional(),
  ovenException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  refrigerator: z.boolean().optional(),
  refrigeratorException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  sink: z.boolean().optional(),
  sinkException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  snackbar: z.boolean().optional(),
  snackbarException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  stove: z.boolean().optional(),
  stoveException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  teaStation: z.boolean().optional(),
  teaStationException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  toaster: z.boolean().optional(),
  toasterException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaFeaturesSchema = z.strictObject({
  airConditioning: z.boolean().optional(),
  airConditioningException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  bathtub: z.boolean().optional(),
  bathtubException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  bidet: z.boolean().optional(),
  bidetException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  dryer: z.boolean().optional(),
  dryerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  electronicRoomKey: z.boolean().optional(),
  electronicRoomKeyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  fireplace: z.boolean().optional(),
  fireplaceException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hairdryer: z.boolean().optional(),
  hairdryerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  heating: z.boolean().optional(),
  heatingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  inunitSafe: z.boolean().optional(),
  inunitSafeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  inunitWifiAvailable: z.boolean().optional(),
  inunitWifiAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  ironingEquipment: z.boolean().optional(),
  ironingEquipmentException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  payPerViewMovies: z.boolean().optional(),
  payPerViewMoviesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  privateBathroom: z.boolean().optional(),
  privateBathroomException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  shower: z.boolean().optional(),
  showerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  toilet: z.boolean().optional(),
  toiletException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tv: z.boolean().optional(),
  tvCasting: z.boolean().optional(),
  tvCastingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tvException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tvStreaming: z.boolean().optional(),
  tvStreamingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  universalPowerAdapters: z.boolean().optional(),
  universalPowerAdaptersException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  washer: z.boolean().optional(),
  washerException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const livingAreaSchema = z.strictObject({
  accessibility: livingAreaAccessibilitySchema.optional(),
  eating: livingAreaEatingSchema.optional(),
  features: livingAreaFeaturesSchema.optional(),
  layout: livingAreaLayoutSchema.optional(),
  sleeping: livingAreaSleepingSchema.optional(),
})

const viewsFromUnitSchema = z.strictObject({
  beachView: z.boolean().optional(),
  beachViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  cityView: z.boolean().optional(),
  cityViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  gardenView: z.boolean().optional(),
  gardenViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  lakeView: z.boolean().optional(),
  lakeViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  landmarkView: z.boolean().optional(),
  landmarkViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  oceanView: z.boolean().optional(),
  oceanViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  poolView: z.boolean().optional(),
  poolViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  valleyView: z.boolean().optional(),
  valleyViewException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const guestUnitFeaturesSchema = z.strictObject({
  bungalowOrVilla: z.boolean().optional(),
  bungalowOrVillaException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  connectingUnitAvailable: z.boolean().optional(),
  connectingUnitAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  executiveFloor: z.boolean().optional(),
  executiveFloorException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  maxAdultOccupantsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  maxAdultOccupantsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  maxChildOccupantsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  maxChildOccupantsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  maxOccupantsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  maxOccupantsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  privateHome: z.boolean().optional(),
  privateHomeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  suite: z.boolean().optional(),
  suiteException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  tier: z.enum(["UNIT_TIER_UNSPECIFIED","STANDARD_UNIT","DELUXE_UNIT"]).optional(),
  tierException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  totalLivingAreas: livingAreaSchema.optional(),
  views: viewsFromUnitSchema.optional(),
})

const guestUnitTypeSchema = z.strictObject({
  codes: z.array(z.string().min(1)).min(1),
  features: guestUnitFeaturesSchema.optional(),
  label: z.string().min(1),
})

const businessSchema = z.strictObject({
  businessCenter: z.boolean().optional(),
  businessCenterException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  meetingRooms: z.boolean().optional(),
  meetingRoomsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  meetingRoomsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  meetingRoomsException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const petsSchema = z.strictObject({
  catsAllowed: z.boolean().optional(),
  catsAllowedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  dogsAllowed: z.boolean().optional(),
  dogsAllowedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  petsAllowed: z.boolean().optional(),
  petsAllowedException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  petsAllowedFree: z.boolean().optional(),
  petsAllowedFreeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const connectivitySchema = z.strictObject({
  freeWifi: z.boolean().optional(),
  freeWifiException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  publicAreaWifiAvailable: z.boolean().optional(),
  publicAreaWifiAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  publicInternetTerminal: z.boolean().optional(),
  publicInternetTerminalException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  wifiAvailable: z.boolean().optional(),
  wifiAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const timeOfDaySchema = z.strictObject({
  hours: z.number().int().min(0).max(23).optional(),
  minutes: z.number().int().min(0).max(59).optional(),
  nanos: z.number().int().min(0).max(999999999).optional(),
  seconds: z.number().int().min(0).max(59).optional(),
})

const paymentOptionsSchema = z.strictObject({
  cash: z.boolean().optional(),
  cashException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  cheque: z.boolean().optional(),
  chequeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  creditCard: z.boolean().optional(),
  creditCardException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  debitCard: z.boolean().optional(),
  debitCardException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  mobileNfc: z.boolean().optional(),
  mobileNfcException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const policiesSchema = z.strictObject({
  allInclusiveAvailable: z.boolean().optional(),
  allInclusiveAvailableException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  allInclusiveOnly: z.boolean().optional(),
  allInclusiveOnlyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  checkinTime: timeOfDaySchema.optional(),
  checkinTimeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  checkoutTime: timeOfDaySchema.optional(),
  checkoutTimeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kidsStayFree: z.boolean().optional(),
  kidsStayFreeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  maxChildAge: z.number().int().min(-2147483648).max(2147483647).optional(),
  maxChildAgeException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  maxKidsStayFreeCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  maxKidsStayFreeCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  paymentOptions: paymentOptionsSchema.optional(),
  smokeFreeProperty: z.boolean().optional(),
  smokeFreePropertyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const familiesSchema = z.strictObject({
  babysitting: z.boolean().optional(),
  babysittingException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kidsActivities: z.boolean().optional(),
  kidsActivitiesException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kidsClub: z.boolean().optional(),
  kidsClubException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  kidsFriendly: z.boolean().optional(),
  kidsFriendlyException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

const poolsSchema = z.strictObject({
  adultPool: z.boolean().optional(),
  adultPoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  hotTub: z.boolean().optional(),
  hotTubException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  indoorPool: z.boolean().optional(),
  indoorPoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  indoorPoolsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  indoorPoolsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  lazyRiver: z.boolean().optional(),
  lazyRiverException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  lifeguard: z.boolean().optional(),
  lifeguardException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  outdoorPool: z.boolean().optional(),
  outdoorPoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  outdoorPoolsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  outdoorPoolsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  pool: z.boolean().optional(),
  poolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  poolsCount: z.number().int().min(-2147483648).max(2147483647).optional(),
  poolsCountException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  wadingPool: z.boolean().optional(),
  wadingPoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterPark: z.boolean().optional(),
  waterParkException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  waterslide: z.boolean().optional(),
  waterslideException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
  wavePool: z.boolean().optional(),
  wavePoolException: z.enum(["EXCEPTION_UNSPECIFIED","UNDER_CONSTRUCTION","DEPENDENT_ON_SEASON","DEPENDENT_ON_DAY_OF_WEEK"]).optional(),
})

export const lodgingSchema = z.strictObject({
  accessibility: accessibilitySchema.optional(),
  activities: activitiesSchema.optional(),
  business: businessSchema.optional(),
  commonLivingArea: livingAreaSchema.optional(),
  connectivity: connectivitySchema.optional(),
  families: familiesSchema.optional(),
  foodAndDrink: foodAndDrinkSchema.optional(),
  guestUnits: z.array(guestUnitTypeSchema).optional(),
  healthAndSafety: healthAndSafetySchema.optional(),
  housekeeping: housekeepingSchema.optional(),
  metadata: lodgingMetadataSchema.optional(),
  parking: parkingSchema.optional(),
  pets: petsSchema.optional(),
  policies: policiesSchema.optional(),
  pools: poolsSchema.optional(),
  property: propertySchema.optional(),
  services: servicesSchema.optional(),
  sustainability: sustainabilitySchema.optional(),
  transportation: transportationSchema.optional(),
  wellness: wellnessSchema.optional(),
}).superRefine((payload, context) => {
  const codes = new Set<string>()
  payload.guestUnits?.forEach((unit, index) => {
    unit.codes.forEach((code, codeIndex) => {
      if (codes.has(code)) {
        context.addIssue({ code: "custom", path: ["guestUnits", index, "codes", codeIndex], message: "Guest unit codes must be unique within a lodging listing." })
      }
      codes.add(code)
    })
  })
})

export type LodgingPayload = z.infer<typeof lodgingSchema>
