"use client"

import type { RefObject } from "react"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import type { ReviewDetail } from "@/lib/contracts/reviews"
import { formatDateTime } from "@/lib/format"
import { actorFor } from "@/lib/inbox/timeline-actor"

type Review = ReviewDetail["review"]

const DRAFT_SOURCE: Record<string, string> = {
  ai: "Generated by AI",
  template: "From a template",
  human: "Written by a person",
}

/**
 * Everything about the review that is true but not worth a line of the header.
 *
 * Only fields the application can actually stand behind. Two absences are
 * deliberate and are named rather than filled in:
 *
 *  · The assignee is real product state (there is an assignee filter and a bulk
 *    "assign" action) but it is not projected onto the review response, so
 *    there is nothing honest to print. The note at the foot says so instead of
 *    borrowing a name from somewhere else.
 *  · Authorship comes from the audit trail — who actually saved the draft —
 *    not from `draft.source` and never from the assignee. Assignment and
 *    authorship are different claims, and an unassigned review can still have
 *    a named author.
 */
function ReviewMetadata({
  review,
  open,
  onOpenChange,
  finalFocus,
}: {
  review: Review
  open: boolean
  onOpenChange: (open: boolean) => void
  /** Where focus returns on close: the menu trigger that opened it. */
  finalFocus?: RefObject<HTMLElement | null>
}) {
  const latestDraft = review.drafts[0]
  const savedBy = actorFor(review, [
    "review.draft.saved",
    "review.draft.created",
  ])
  const publishedBy = actorFor(review, ["review.reply.published"])
  const approvedBy = actorFor(review, ["review.approval.approved"])

  const rows: { term: string; value: string }[] = [
    {
      term: "Review received",
      value: formatDateTime(review.createTime, review.timezone),
    },
    {
      term: "Google profile",
      value:
        review.verified === true
          ? `${review.locationName} · verified`
          : review.verified === false
            ? `${review.locationName} · not verified`
            : review.locationName,
    },
  ]

  if (latestDraft) {
    rows.push({
      term: "Reply source",
      value: DRAFT_SOURCE[latestDraft.source] ?? "Saved draft",
    })
    rows.push({
      term: "Draft last saved by",
      value: savedBy ?? "Not recorded",
    })
  }
  if (approvedBy) rows.push({ term: "Approved by", value: approvedBy })
  if (publishedBy) rows.push({ term: "Published by", value: publishedBy })

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md" finalFocus={finalFocus}>
        <DialogHeader>
          <DialogTitle>Review details</DialogTitle>
          <DialogDescription>
            When the review arrived, its Google profile and who worked on the
            reply.
          </DialogDescription>
        </DialogHeader>
        <dl className="flex flex-col gap-3">
          {rows.map((row) => (
            <div key={row.term} className="flex flex-col gap-0.5">
              <dt className="text-caption text-ink-muted">{row.term}</dt>
              <dd className="text-ui leading-normal break-words text-ink">
                {row.value}
              </dd>
            </div>
          ))}
        </dl>
        <p className="border-t border-line-subtle pt-2 text-caption text-ink-muted">
          Who a review is assigned to is not part of this review&rsquo;s data
          yet, so it is not shown here. You can still filter the list by
          assignee.
        </p>
      </DialogContent>
    </Dialog>
  )
}

export { ReviewMetadata }
